#!/bin/bash
# Xombra
# Licence: GPL-2
# block url
# bloquear url
LC_ALL=C
if [[ $USER != root ]]; then
	echo -e "\e[00;31mERROR: You must be root to run script\e[00m"
	exit 1
fi

if [[ -z $1 ]]; then
	echo "ERROR: Debes indicar una ip o dominio"
	exit 1
fi

trap "rm -f /run/$0.pid; exit" INT TERM EXIT
echo "$BASHPID" > /run/$0.pid
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")


if [[ -f /etc/hosts ]]; then
# exist
else
	echo 'Host file does not exist will be created'
	touch /etc/hosts
fi

# formato para este archivo:
# IP  domain
# Es valido el uso de comodines en dominio
# It is allowed to use wildcards (*) when specifying the domain.
# Write file /etc/hosts

echo "127.0.0.1" $1 >> /etc/hosts
echo $1 " It was written in the host file"

IFS=$SAVEIFS
rm -f /run/$0.pid
trap - INT TERM EXIT
exit 0
